# Generated by Django 2.2.1 on 2019-06-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_auto_20190612_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeuplecture',
            name='lec_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='makeuplecture',
            unique_together={('year', 'division', 'lec_date', 'lec_time')},
        ),
    ]
