# Generated by Django 2.2.1 on 2019-06-15 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_date', models.DateField()),
                ('lec_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.Room')),
                ('lec_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Subject')),
                ('lec_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.TimeSlot')),
                ('lec_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Year')),
            ],
            options={
                'unique_together': {('lec_year', 'lec_date', 'lec_time')},
            },
        ),
    ]
