# Generated by Django 2.2.1 on 2019-07-26 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0016_auto_20190706_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadshift',
            name='to_faculty',
        ),
        migrations.AddField(
            model_name='loadshift',
            name='to_faculty',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
