# Generated by Django 2.2.1 on 2019-07-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_auto_20190726_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approved_status',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='od',
            name='approved_status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
