# Generated by Django 2.2.1 on 2019-07-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_auto_20190727_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.TextField(null=True),
        ),
    ]
