# Generated by Django 2.2.1 on 2019-07-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0021_iabatchroommapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ia',
            name='ia_in',
        ),
    ]
