# Generated by Django 2.2.1 on 2019-07-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0022_remove_ia_ia_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='ia',
            name='ia_end_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ia',
            name='ia_start_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='ia',
            unique_together={('ia_year', 'ia_date', 'ia_start_time', 'ia_end_time')},
        ),
        migrations.RemoveField(
            model_name='ia',
            name='ia_time',
        ),
    ]
