# Generated by Django 2.2.1 on 2019-07-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0024_auto_20190727_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iabatchroommapping',
            old_name='suervisor',
            new_name='supervisor',
        ),
    ]
