# Generated by Django 2.2.1 on 2019-08-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0025_auto_20190727_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='supporting_file',
            field=models.FileField(blank=True, null=True, upload_to='leaves/medical/'),
        ),
    ]
