# Generated by Django 2.2.1 on 2019-10-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0027_auto_20191021_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlecture',
            name='title',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
