# Generated by Django 2.2.1 on 2019-07-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default='2019-01-01'),
            preserve_default=False,
        ),
    ]
