# Generated by Django 2.2.1 on 2019-08-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_auto_20190729_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
