# Generated by Django 2.2.1 on 2019-06-07 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_note', models.TextField()),
                ('approved_status', models.BooleanField(default=False)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('leave_start_time', models.TimeField()),
                ('leave_end_time', models.TimeField()),
                ('leave_taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.DaysOfWeek')),
                ('lec_div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.Division')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=255)),
                ('teaching_faculty', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(null=True, on_delete='models.CASCADE', to='faculty.Year')),
            ],
        ),
        migrations.CreateModel(
            name='LoadShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_lecture', to='faculty.Lecture')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Leave')),
                ('to_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='lec_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.TimeSlot'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Subject'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='taken_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
