# Generated by Django 2.2.1 on 2019-06-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='div_of',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', to='faculty.Year'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=255)),
                ('batch_of_div', models.ForeignKey(null=True, on_delete='models.CASCADE', to='faculty.Division')),
                ('batch_of_year', models.ForeignKey(null=True, on_delete='models.CASCADE', to='faculty.Year')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='lec_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.Room'),
        ),
    ]
