# Generated by Django 2.2.1 on 2019-06-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20190607_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lec_batch',
            field=models.ManyToManyField(to='faculty.Batch'),
        ),
    ]
