# Generated by Django 2.2.1 on 2019-06-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_lecture_lec_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lec_batch',
        ),
        migrations.AddField(
            model_name='lecture',
            name='lec_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.Batch'),
        ),
    ]
