# Generated by Django 2.2.1 on 2019-06-11 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0004_auto_20190608_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_date', models.DateField()),
                ('lec_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Subject')),
                ('lec_taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lec_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.TimeSlot')),
            ],
            options={
                'unique_together': {('lec_date', 'lec_time')},
            },
        ),
    ]
