# Generated by Django 2.2.1 on 2019-06-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_auto_20190613_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='IA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia_date', models.DateField()),
                ('ia_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.Room')),
                ('ia_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Subject')),
                ('ia_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.TimeSlot')),
                ('ia_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Year')),
            ],
            options={
                'unique_together': {('ia_year', 'ia_date', 'ia_time')},
            },
        ),
    ]
