# Generated by Django 2.2.1 on 2019-06-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_guestlecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_type', models.CharField(max_length=20)),
                ('od_title', models.CharField(max_length=255)),
                ('od_details', models.TextField(max_length=255)),
                ('supporting_organisation', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('last_date', models.DateField()),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, max_length=255, null=True)),
                ('correspondence', models.FileField(upload_to='od/correspondence/')),
            ],
        ),
    ]
