# Generated by Django 2.2.1 on 2019-06-23 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0010_guestlecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_type', models.CharField(max_length=20)),
                ('od_title', models.CharField(max_length=255)),
                ('od_details', models.TextField(max_length=255)),
                ('supporting_organisation', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('last_date', models.DateField()),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, max_length=255, null=True)),
                ('correspondence', models.FileField(upload_to='od/correspondence/')),
                ('approved_status', models.BooleanField(default=False)),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
