# Generated by Django 2.2.1 on 2019-06-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_od'),
    ]

    operations = [
        migrations.AlterField(
            model_name='od',
            name='correspondence',
            field=models.FileField(blank=True, null=True, upload_to='od/correspondence/'),
        ),
    ]
