# Generated by Django 2.2.1 on 2019-06-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_auto_20190623_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadshift',
            name='od',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.OD'),
        ),
        migrations.AlterField(
            model_name='loadshift',
            name='leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.Leave'),
        ),
    ]
