# Generated by Django 2.2.1 on 2019-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_auto_20190627_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadshift',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
    ]
