# Generated by Django 2.2.1 on 2019-07-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_loadshift_approved_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lec_batch',
        ),
        migrations.AddField(
            model_name='lecture',
            name='lec_batch',
            field=models.ManyToManyField(to='faculty.Batch'),
        ),
    ]
