# Generated by Django 2.2.1 on 2019-10-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=254)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('to', models.TextField()),
                ('subject', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('status', models.BooleanField(null=True)),
            ],
        ),
    ]
