# Generated by Django 2.2.1 on 2019-10-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='email_from',
            new_name='from_email',
        ),
    ]
