# Generated by Django 2.2.1 on 2019-10-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailManager', '0002_auto_20191028_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
